### ISSUE TITLE
Picture of the esp8266 mod?

### ISSUE THREAD

**Issue by pornstrup** [jascdk/WAVIN-AHC-9000-Floor-Heating---Home-assistant-compatible-homekit#1]
Hi Jascdk. Do you have a picture of how you have made the esp8266 that connects with the AHC 9000? Thanks Peter

**Comment by jascdk** [comment]
Hi :) yes you Can see it here ;)
![0F8B8410-D261-4DA8-9763-65C0535120B1](https://user-images.githubusercontent.com/35434108/66191023-9b317e00-e68d-11e9-8f77-ba5924305ffa.jpeg)
