### ISSUE TITLE
Need help with setup

### ISSUE THREAD

**Issue by Berjastein** [jascdk/WAVIN-AHC-9000-Floor-Heating---Home-assistant-compatible-homekit#2]
Hi, I have tried to get this to work, but all i get when i try "mosquitto_sub -u username -P password -t heat/# -v" is "heat/floorXXXXXXXXXXXX/online True, should i be getting more data?

Edit:
I get data from all the outputs now, but in home assistant it says connected and no devices popping up on auto discovery.

**Comment by jascdk** [comment]
@Berjastein hi :) have you tried to manually input the yaml code ?
